### ISSUE TITLE
CSS code formatting. 

### ISSUE THREAD

**Issue by josephtkim** [djschaef/prj-rev-bwfs-dasmoto#5]
For the CSS code always place each property on a new line, and stay consistent with how you apply indentation and spacing between selectors. Here is how the code might be cleaned up,

```css
h1 {
  font-family: Helvetica;
  font-size: 100px;
  font-weight: bold;
  color: khaki;
  text-align: center;
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
}

h2 {
  font-family:  Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}

h3 {
  font-family: Helvetica;
  font-size: 16;
}

p {
  font-family: Helvetica;
  font-size: 12;
}

#brush {
  background-color: mediumspringgreen;
}

#frame { 
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}

.price {
  font-family: Helvetica;
  font-weight: bold;
  color: blue;
}
```
