### ISSUE TITLE
Simplify CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [djschaef/prj-rev-bwfs-dasmoto#6]
It is a good idea to try and simplify the CSS code to make the code cleaner and to remove repetitive code. In addition, for the font-size properties of the h3 and p element, make sure to include units like px.

```css
body {
  font-family: Helvetica;
  font-weight: bold;
}

h1 {
  font-size: 100px;
  color: khaki;
  text-align: center;
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
}

h2 {
  font-size: 32px;
  color: white;
}

h3 {
  font-size: 16px;
}

p {
  font-size: 12px;
}

#brush {
  background-color: mediumspringgreen;
}

#frame { 
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}

.price {
  color: blue;
}
```
